In [1]:
import csv
import pandas as pd
import numpy as np

req_cols = ["Name", "DSK Category", "Agriculture", "iLUC", "Food processing", "Packaging",
           "Transport", "Retail", "Total kg CO2-eq/kg", "Energi (KJ/100 g)", "Fedt (g/100 g)", "Kulhydrat (g/100 g)",
           "Protein (g/100 g)"]

df= pd.read_csv("food_data.csv", index_col=None, header=0, usecols=req_cols)

In [2]:
df.head(20)

,Name,DSK Category,Agriculture,iLUC,Food processing,Packaging,Transport,Retail,Total kg CO2-eq/kg,Energi (KJ/100 g),Fedt (g/100 g),Kulhydrat (g/100 g),Protein (g/100 g)
0,"Pepper, sweet, red, raw",Vegetables,0.25,0.03,0.00,0.14,0.58,0.01,1.02,133.0,0.1,5.2,0.9
1,"Tomato, ripe, raw, origin unknown",Vegetables,0.07,0.01,0.00,0.14,0.48,0.01,0.70,87.0,0.1,3.2,0.8
2,"Squash, raw",Vegetables,0.14,0.04,0.00,0.06,0.58,0.01,0.83,81.0,0.2,2.4,1.4
3,"Aubergine, raw",Vegetables,0.16,0.02,0.00,0.14,0.65,0.01,0.97,83.0,0.1,3.1,0.9
4,"Tomato, dried",Vegetables,0.91,0.09,0.00,0.26,0.68,0.01,1.95,1187.0,3.0,43.5,14.1
5,"Pumpkin, raw",Vegetables,0.14,0.04,0.00,0.06,0.58,0.01,0.83,75.0,0.1,3.3,0.6
6,"Cucumber, raw",Vegetables,0.05,0.01,0.00,0.14,0.35,0.01,0.56,50.0,0.0,1.6,0.7
7,"Gherkin cucumber, raw",Vegetables,0.05,0.01,0.00,0.14,0.35,0.01,0.56,70.0,0.1,2.1,1.2
8,"Pepper, hot chili, raw",Vegetables,0.25,0.03,0.00,0.14,0.58,0.01,1.02,187.0,0.2,7.7,2
9,"Beef, topside, cap off, raw",Meat/poultry,39.65,7.68,-2.41,0.14,0.63,0.00,45.69,472.0,2.5,0,22.3
10,"Beef, fillet, defatted, raw",Meat/poultry,133.45,25.85,-8.11,0.14,0.63,0.00,151.95,576.0,6.4,0,20
11,"Beef, mince, 10-15% fat, raw",Meat/poultry,28.58,5.46,-1.78,0.14,0.12,0.00,32.51,687.0,9.7,0,19.4
12,"Beef, rump, raw",Meat/poultry,39.65,7.68,-2.41,0.14,0.63,0.00,45.69,879.0,14.9,0,19.3
13,"Beef, mince, 15-20% fat, raw",Meat/poultry,26.90,5.16,-1.47,0.14,0.12,0.00,30.84,903.0,16.2,0,17.8
14,"Beef, T-bone steak, raw",Meat/poultry,70.72,13.70,-4.30,0.14,0.63,0.00,80.89,878.0,14.4,0,20.3
15,"Beef, mince, 5-10% fat, raw",Meat/poultry,30.26,5.75,-2.09,0.14,0.12,0.00,34.19,683.0,9.5,0,19.5
16,"Beer, lager, alc. 4.4 % by vol.",Beverages,0.07,0.05,0.24,0.16,0.07,0.01,0.60,152.0,0.0,2.7,0.3
17,"Beer, Danish household, low alcohol",Beverages,0.07,0.05,0.24,0.16,0.07,0.01,0.60,189.0,0.0,8.6,0.3
18,"Beer, strong, alc. 7.6 % by vol.",Beverages,0.07,0.05,0.24,0.16,0.07,0.01,0.60,260.0,0.0,4.6,0.4
19,"Biscuit, sweet",Bread/bakery products,0.59,0.12,1.22,0.67,0.14,0.01,2.75,1834.0,10.6,72.5,7.7

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595 entries, 0 to 594
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 500 non-null    object
 1   DSK Category         500 non-null    object
 2   Agriculture          500 non-null    float64
 3   iLUC                 500 non-null    float64
 4   Food processing      500 non-null    float64
 5   Packaging            500 non-null    float64
 6   Transport            500 non-null    float64
 7   Retail               500 non-null    float64
 8   Total kg CO2-eq/kg   500 non-null    float64
 9   Energi (KJ/100 g)    500 non-null    float64
 10  Fedt (g/100 g)       500 non-null    float64
 11  Kulhydrat (g/100 g)  500 non-null    object
 12  Protein (g/100 g)    500 non-null    object
dtypes: float64(9), object(4)
memory usage: 60.6+ KB
None

In [4]:
num_cols=['Protein (g/100 g)', 'Kulhydrat (g/100 g)']

for cols in num_cols:
    df = df[pd.to_numeric(df[cols], errors='coerce').notnull()]
    df = df.astype({cols : float}, errors='raise')

In [5]:
cat_cols=["DSK Category"]

for cols in cat_cols:
    df = df.astype({cols : 'category'}, errors='raise')

In [6]:
s_cols=["Name"]

for cols in s_cols:
    df = df.astype({cols : 'string'}, errors='raise')

In [8]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 499 entries, 0 to 499
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 499 non-null    string
 1   DSK Category         499 non-null    category
 2   Agriculture          499 non-null    float64
 3   iLUC                 499 non-null    float64
 4   Food processing      499 non-null    float64
 5   Packaging            499 non-null    float64
 6   Transport            499 non-null    float64
 7   Retail               499 non-null    float64
 8   Total kg CO2-eq/kg   499 non-null    float64
 9   Energi (KJ/100 g)    499 non-null    float64
 10  Fedt (g/100 g)       499 non-null    float64
 11  Kulhydrat (g/100 g)  499 non-null    float64
 12  Protein (g/100 g)    499 non-null    float64
dtypes: category(1), float64(11), string(1)
memory usage: 51.8 KB
None

In [9]:
print(df.value_counts("DSK Category"))

DSK Category
Fruit/vegetable products             75
Meat/poultry                         61
Prepared/preserved foods             61
Vegetables                           56
Seafood                              51
Bread/bakery products                34
Beverages                            32
Seasonings/preservatives/extracts    32
Milk/eggs/substitute products        31
Fruits                               27
Cereal/grain/pulse products          22
Candy/sugar products                 13
Oils/fats edible                      4
dtype: int64