In [1]:
import csv
import pandas as pd
import numpy as np

req_cols = ["Navn", "DSK Kategori", "Name", "DSK Category", "Agriculture", "iLUC", "Food processing", "Packaging",
           "Transport", "Retail", "Total kg CO2-eq/kg", "Energi (KJ/100 g)", "Fedt (g/100 g)", "Kulhydrat (g/100 g)",
           "Protein (g/100 g)"]

df= pd.read_csv("food_data.csv", index_col=None, header=0, usecols=req_cols)

In [2]:
df.head(5)

,Navn,DSK Kategori,Name,DSK Category,Agriculture,iLUC,Food processing,Packaging,Transport,Retail,Total kg CO2-eq/kg,Energi (KJ/100 g),Fedt (g/100 g),Kulhydrat (g/100 g),Protein (g/100 g)
0,"Peberfrugt, r�d, r�",Gr�ntsager,"Pepper, sweet, red, raw",Vegetables,0.25,0.03,0.0,0.14,0.58,0.01,1.02,133.0,0.1,5.2,0.9
1,"Tomat, uspec., r�",Gr�ntsager,"Tomato, ripe, raw, origin unknown",Vegetables,0.07,0.01,0.0,0.14,0.48,0.01,0.70,87.0,0.1,3.2,0.8
2,"Squash, r�",Gr�ntsager,"Squash, raw",Vegetables,0.14,0.04,0.0,0.06,0.58,0.01,0.83,81.0,0.2,2.4,1.4
3,"Aubergine, r�",Gr�ntsager,"Aubergine, raw",Vegetables,0.16,0.02,0.0,0.14,0.65,0.01,0.97,83.0,0.1,3.1,0.9
4,"Tomat, solt�rret",Gr�ntsager,"Tomato, dried",Vegetables,0.91,0.09,0.0,0.26,0.68,0.01,1.95,1187.0,3.0,43.5,14.1

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595 entries, 0 to 594
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Navn                 500 non-null    object
 1   DSK Kategori         500 non-null    object
 2   Name                 500 non-null    object
 3   DSK Category         500 non-null    object
 4   Agriculture          500 non-null    float64
 5   iLUC                 500 non-null    float64
 6   Food processing      500 non-null    float64
 7   Packaging            500 non-null    float64
 8   Transport            500 non-null    float64
 9   Retail               500 non-null    float64
 10  Total kg CO2-eq/kg   500 non-null    float64
 11  Energi (KJ/100 g)    500 non-null    float64
 12  Fedt (g/100 g)       500 non-null    float64
 13  Kulhydrat (g/100 g)  500 non-null    object
 14  Protein (g/100 g)    500 non-null    object
dtypes: float64(9), object(6)
memory usage: 69.9+ KB
None

In [6]:
num_cols=['Protein (g/100 g)', 'Kulhydrat (g/100 g)']

for cols in num_cols:
    df = df[pd.to_numeric(df[cols], errors='coerce').notnull()]
    df = df.astype({cols : float}, errors='raise')

In [7]:
cat_cols=["DSK Kategori", "DSK Category"]

for cols in cat_cols:
    df = df.astype({cols : 'category'}, errors='raise')

In [8]:
s_cols=["Navn", "Name"]

for cols in s_cols:
    df = df.astype({cols : 'string'}, errors='raise')

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 499 entries, 0 to 499
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Navn                 499 non-null    string
 1   DSK Kategori         499 non-null    category
 2   Name                 499 non-null    string
 3   DSK Category         499 non-null    category
 4   Agriculture          499 non-null    float64
 5   iLUC                 499 non-null    float64
 6   Food processing      499 non-null    float64
 7   Packaging            499 non-null    float64
 8   Transport            499 non-null    float64
 9   Retail               499 non-null    float64
 10  Total kg CO2-eq/kg   499 non-null    float64
 11  Energi (KJ/100 g)    499 non-null    float64
 12  Fedt (g/100 g)       499 non-null    float64
 13  Kulhydrat (g/100 g)  499 non-null    float64
 14  Protein (g/100 g)    499 non-null    float64
dtypes: category(2), float64(11), string(2)
memory usage: 56.8 KB
None